In [1]:
import pandas as pd

In [3]:
df_ton = pd.read_excel('/content/datos_volumen_ton_sniim_2001_2026.xlsx')

df_ton.head()

,Fecha,Presentacion,Origen,Destino,Transporte,Volumen ton
0,15/01/2001,Caja de 24 kg.,Michoacán,México: Central de Abasto de Ecatepec,Rabón,7.0
1,16/01/2001,Caja de 20 kg.,Michoacán,Jalisco: Mercado de Abasto de Guadalajara,Trailer,1365.0
2,17/01/2001,Caja de 24 kg.,Distrito Federal,México: Central de Abasto de Ecatepec,Rabón,3.0
3,17/01/2001,Caja de 24 kg.,Distrito Federal,México: Central de Abasto de Ecatepec,Redilas,7.0
4,17/01/2001,Caja de 24 kg.,Michoacán,México: Central de Abasto de Ecatepec,Rabón,8.0

In [4]:
df_ton.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9408 entries, 0 to 9407
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha         9408 non-null   object
 1   Presentacion  9408 non-null   object
 2   Origen        9408 non-null   object
 3   Destino       9408 non-null   object
 4   Transporte    9408 non-null   object
 5   Volumen ton   9408 non-null   float64
dtypes: float64(1), object(5)
memory usage: 441.1+ KB

In [5]:
print(f'Se van a analizar {df_ton.shape[0]} registros')
print('---' * 10)

#duplicados
print('Analizamos los datos duplicados')
print('---' * 10)
total_duplicados = df_ton.duplicated().sum()
print(f"Total de filas duplicadas: {total_duplicados}")

df_sin_dupes = df_ton.drop_duplicates()
print(f"Total de filas sin duplicados: {df_sin_dupes.shape[0]}")

porcentaje = (total_duplicados / df_ton.shape[0]) * 100
print(f"Porcentaje de filas duplicadas: {porcentaje:.2f}%")

pct_retencion = 100 - porcentaje
print(f"Porcentaje de filas retenidas: {pct_retencion:.2f}%")

Se van a analizar 9408 registros
------------------------------
Analizamos los datos duplicados
------------------------------
Total de filas duplicadas: 16
Total de filas sin duplicados: 9392
Porcentaje de filas duplicadas: 0.17%
Porcentaje de filas retenidas: 99.83%

In [9]:
#Transformamos a tipo DateTime

df_sin_dupes['Fecha'] = pd.to_datetime(df_ton['Fecha'])

df_sin_dupes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9392 entries, 0 to 9407
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha         9392 non-null   datetime64[ns]
 1   Presentacion  9392 non-null   object
 2   Origen        9392 non-null   object
 3   Destino       9392 non-null   object
 4   Transporte    9392 non-null   object
 5   Volumen ton   9392 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 513.6+ KB

/tmp/ipykernel_1122/3496701286.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sin_dupes['Fecha'] = pd.to_datetime(df_ton['Fecha'])

In [11]:
from numpy import transpose
#Verificamos los tipos de presentaciones
presentaciones = df_sin_dupes['Presentacion'].unique()
print('--- Verificando tipos de presentaciones ---')
print(f'Hay {len(presentaciones)} presentaciones, las cuales son: {presentaciones}')

#verificamos productores
productores = df_sin_dupes['Origen'].unique()
print('--- Verificando productores ---')
print(f'Hay {len(productores)} estados que participan, que son: {productores}')

#Verificamos los tipos de transporte
transportes = df_sin_dupes['Transporte'].unique()
print('--- Verificando tipos de transporte ---')
print(f'Hay {len(transportes)} tipos de transporte, que son: {transportes}')


#Verificamos cuáles años tenemos
años = df_sin_dupes['Fecha'].dt.year.unique()
print('--- Verificando años ---')
print(f'Hay {len(años)} años, que son: {años}')

--- Verificando tipos de presentaciones ---
Hay 31 presentaciones, las cuales son: ['Caja de 24 kg.' 'Caja de 20 kg.' 'Caja de 18 kg.' 'Caja de 10 kg.'
 'Caja de 15 kg.' 'Caja de 22 kg.' 'Caja de 23 kg.' 'Kilogramo'
 'Caja de 25 kg.' 'Caja de 12 kg.' 'Arpilla de 20 kg.' 'Caja de 20 pzas.'
 'Caja de 21 kg.' 'Manojo de 10 pzas.' 'Arpilla de 10 kg.'
 'Caja de 13 kg.' 'Caja de 30 kg.' 'Caja de 19 kg.' 'Arpilla de 15 kg.'
 'Caja de 18 pzas.' 'Caja de 14 kg.' 'Caja de 16 kg.' 'Rollo'
 'Caja de 10 pzas.' 'Caja de 9 kg.' 'Caja de 11 kg.' 'Caja de 9 pzas.'
 'Caja de 8 kg.' 'Cesta de 9 kg.' 'Arpilla de 25 kg.' 'Arpilla de 30 kg.']
--- Verificando productores ---
Hay 27 estados que participan, que son: ['Michoacán' 'Distrito Federal' 'Yucatán' 'Nayarit' 'Jalisco' 'Colima'
 'Chiapas' 'Oaxaca' 'Nuevo León' 'Aguascalientes' 'Chihuahua' 'Sinaloa'
 'Tabasco' 'Zacatecas' 'Veracruz' 'San Luis Potosí' 'México'
 'Sin Especificar' 'Baja California' 'Tamaulipas' 'Sonora' 'Guerrero'
 'Campeche' 'Guanajuato' 'Morelos' 'Puebla' 'Importación']
--- Verificando tipos de transporte ---
Hay 4 tipos de transporte, que son: ['Rabón' 'Trailer' 'Redilas' 'Torton']
--- Verificando años ---
Hay 26 años, que son: [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026]

In [12]:
#Revisamos datos nulos

df_sin_dupes.isna().sum()

Fecha           0
Presentacion    0
Origen          0
Destino         0
Transporte      0
Volumen ton     0
dtype: int64

In [13]:
#guardamos

df_sin_dupes.to_csv('volumen_ton_sniim.csv', index=False, encoding='utf-8')